### ISSUE TITLE
StackOverflow in seen-3

### ISSUE THREAD

**Issue by rgrig** [ukc-co663/dependency-solver-RyanTaplin1705#7]
Test seen-3 fails with an exception:

> root@66eacdfd3d71:/depsolver/to-test# ./solve ../tests/seen-3/repository.json ../tests/seen-3/initial.json ../tests/seen-3/constraints.json 2>&1 | head -10
> Exception in thread "main" java.lang.StackOverflowError
> 	at model.states.State.addPackage(State.java:70)
> 	at model.states.State.addPackage(State.java:73)
> 	at model.states.State.addPackage(State.java:73)
> 	at model.states.State.addPackage(State.java:73)

**Comment by ryantaplin** [comment]
Also occurring in seen-6 and seen-1 as of fix #9.

**Comment by ryantaplin** [comment]
```
Seen-1 and Seen-3
java.lang.StackOverflowError
	at model.states.State.addPackage(State.java:84)
	at model.states.State.addPackage(State.java:87)
	at model.states.State.addPackage(State.java:87)

Seen-6
java.lang.StackOverflowError
	at java.util.LinkedList.addAll(LinkedList.java:387)
	at java.util.LinkedList.<init>(LinkedList.java:119)
	at model.states.State.clone(State.java:192)
	at model.states.State.addPackage(State.java:118)
	at model.states.State.addPackage(State.java:87)
	at model.states.State.addPackage(State.java:87)
	at model.states.State.addPackage(State.java:87)
```
Line 87 `result.addAll(this.clone().addPackage(p2, packageRepository));`
This is inside method `.addPackage(p, pr)` so I don't think it likes the recursion on this? Not sure how to counter this right now. 
```
Seen-9
java.lang.StackOverflowError
	at java.util.LinkedList.listIterator(LinkedList.java:868)
	at java.util.AbstractList.listIterator(AbstractList.java:299)
	at java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:239)
	at model.states.State.violatesConstraint(State.java:58)
	at model.states.State.deletePackage(State.java:66)
	at model.states.State.removePackage(State.java:37)
	at model.states.State.removePackage(State.java:53)
	at model.states.State.removePackage(State.java:53)
```
Line 53 `for (State s : result) s.removePackage(p, packageRepository);`.
As above, this is inside method `.removePackage(p, pr)` so I don't think it likes that recursive call.

@rgrig not sure what to do to fix these right now, have any suggestions?

**Comment by ryantaplin** [comment]
~~Seen-1, Seen-3 and Seen-6 fixed as of 6b9a487b21a071fc5f5b64840b95c94555ad7053.~~

Still seen-9 fixed as of b9c69ccb042e9fa4714105b1e137bb937c247c86.
My fixes for seen-1, 3 and 6 was incorrect so I reverted to original recursive impl for now. Need to think about a work around.
